#!/usr/bin/env python3
"""Generate the recommended Rust lint configuration and pre-commit hook.

This script is the source of truth for the lint levels documented in
docs/recommended-lint-config.md. Edit the data structures here, then
regenerate outputs.

The --fixable-lints flag points to the scraped MachineApplicable lint list
(generated by scrape-clippy-applicability.py --format cargo-toml). Those
lints are set to "allow" so they stay silent during dev, then auto-fixed
by the pre-commit hook. Recommended lint levels always take precedence.

Usage:
    # Without fixable lints (recommended deny/warn only):
    python3 scripts/recommended-config.py --format lints
    python3 scripts/recommended-config.py --format hook

    # With fixable lints (adds allow entries + restriction -W flags):
    python3 scripts/recommended-config.py --format lints --fixable-lints fixable-lints.cargo.toml
    python3 scripts/recommended-config.py --format hook  --fixable-lints fixable-lints.cargo.toml
    python3 scripts/recommended-config.py --install      --fixable-lints fixable-lints.cargo.toml
"""

from __future__ import annotations

import argparse
import re
import stat
import sys
from collections import OrderedDict
from pathlib import Path


# -- Recommended lint levels --

RUST_LINTS: OrderedDict[str, str] = OrderedDict([
    ("unsafe_code", "forbid"),
    ("unused_must_use", "deny"),
])

CLIPPY_LINTS: OrderedDict[str, list[tuple[str, str]]] = OrderedDict([
    ("Deny: always wrong in production", [
        ("await_holding_lock", "deny"),
        ("await_holding_refcell_ref", "deny"),
        ("let_underscore_future", "deny"),
        ("rc_mutex", "deny"),
        ("exit", "deny"),
        ("todo", "deny"),
        ("unimplemented", "deny"),
        ("undocumented_unsafe_blocks", "deny"),
        ("multiple_unsafe_ops_per_block", "deny"),
    ]),
    ("Error handling discipline", [
        ("unwrap_used", "warn"),
        ("expect_used", "warn"),
        ("panic_in_result_fn", "warn"),
        ("unwrap_in_result", "warn"),
        ("map_err_ignore", "warn"),
    ]),
    ("Type safety & correctness", [
        ("indexing_slicing", "warn"),
        ("panic", "warn"),
        ("option_option", "warn"),
        ("cast_possible_truncation", "warn"),
        ("cast_sign_loss", "warn"),
        ("cast_possible_wrap", "warn"),
        ("float_cmp", "warn"),
    ]),
    ("Async & concurrency", [
        ("large_futures", "warn"),
        ("mutex_atomic", "warn"),
    ]),
    ("Code quality & maintainability", [
        ("wildcard_enum_match_arm", "warn"),
        ("clone_on_ref_ptr", "warn"),
        ("unused_result_ok", "warn"),
        ("let_underscore_must_use", "warn"),
        ("fn_params_excessive_bools", "warn"),
        ("match_same_arms", "warn"),
        ("match_wildcard_for_single_variants", "warn"),
    ]),
    ("Documentation & design", [
        ("missing_errors_doc", "warn"),
        ("missing_panics_doc", "warn"),
        ("missing_fields_in_debug", "warn"),
        ("return_self_not_must_use", "warn"),
        ("should_panic_without_expect", "warn"),
        ("allow_attributes_without_reason", "deny"),
        ("ignore_without_reason", "deny"),
    ]),
    ("Performance & idioms", [
        ("unnecessary_wraps", "warn"),
        ("manual_let_else", "warn"),
        ("default_trait_access", "warn"),
        ("format_push_string", "warn"),
        ("unreadable_literal", "warn"),
    ]),
    ("Debug & print discipline", [
        ("dbg_macro", "warn"),
        ("print_stdout", "warn"),
        ("print_stderr", "warn"),
    ]),
    ("File & I/O operations", [
        ("create_dir", "warn"),
        ("verbose_file_reads", "warn"),
        ("pathbuf_init_then_push", "warn"),
    ]),
    ("Resource management", [
        ("mem_forget", "warn"),
        ("rc_buffer", "warn"),
        ("large_include_file", "warn"),
    ]),
    ("Miscellaneous", [
        ("error_impl_error", "warn"),
        ("cfg_not_test", "warn"),
        ("missing_assert_message", "warn"),
        ("tests_outside_test_module", "warn"),
        ("ref_option", "warn"),
        ("large_types_passed_by_value", "warn"),
        ("unsafe_derive_deserialize", "warn"),
        ("large_stack_arrays", "warn"),
        ("doc_link_with_quotes", "warn"),
        ("copy_iterator", "warn"),
        ("macro_use_imports", "warn"),
    ]),
])

# Contradictory lint pairs — one from each must be excluded. The scraper
# reports both as MachineApplicable, but enabling both causes them to fight
# (each fix triggers the other). We keep the idiomatic/majority choice.
EXCLUDED_FIXABLE_LINTS = {
    "implicit_return",          # contradicts needless_return (keep needless_return)
    "semicolon_inside_block",   # contradicts semicolon_outside_block (keep outside)
    "pub_without_shorthand",    # contradicts pub_with_shorthand (keep with)
    "separated_literal_suffix",    # contradicts unseparated_literal_suffix (keep unseparated)
}

BANNED_CRATES: OrderedDict[str, str] = OrderedDict([
    ("lazy_static", "use std::sync::LazyLock (Rust 1.80+)"),
    ("once_cell", "use std::sync::OnceLock / LazyLock (Rust 1.70+/1.80+)"),
    ("failure", "use thiserror for libraries, anyhow for applications"),
    ("dashmap", "use RwLock<HashMap> — DashMap deadlocks when a Ref is held across map calls"),
    ("openssl", "use rustls"),
    ("md5", "MD5 is cryptographically broken; use SHA-256 or SHA-3"),
    ("sha1", "SHA-1 collision resistance is broken; use SHA-256 or SHA-3"),
])


def parse_fixable_lints(path: Path) -> OrderedDict[str, list[str]]:
    """Parse the fixable lints TOML file into {group: [lint_name, ...]}."""
    groups: OrderedDict[str, list[str]] = OrderedDict()
    current_group = "ungrouped"
    for line in path.read_text().splitlines():
        comment = re.match(r"^#\s*(\w[\w ]*)\((\d+) lints?\)", line)
        if comment:
            current_group = comment.group(1).strip()
            groups.setdefault(current_group, [])
            continue
        m = re.match(r'^(\w+)\s*=\s*"allow"', line)
        if m and m.group(1) not in EXCLUDED_FIXABLE_LINTS:
            groups.setdefault(current_group, []).append(m.group(1))
    return groups


def emit_lints(fixable_lints_path: Path | None = None) -> str:
    """Emit the recommended [lints.rust] + [lints.clippy] TOML sections.

    If fixable_lints_path is provided, MachineApplicable lints are included
    as "allow" (silent during dev, auto-fixed at commit time). Recommended
    lint levels take precedence over the fixable list.
    """
    # Collect all recommended lint names for precedence check
    recommended_names = {
        lint
        for group_lints in CLIPPY_LINTS.values()
        for lint, _ in group_lints
    }

    lines = [
        f"# Auto-generated by scripts/recommended-config.py --format lints{f' --fixable-lints {fixable_lints_path}' if fixable_lints_path else ''}",
        "",
        "[lints.rust]",
    ]
    pad = max(len(k) for k in RUST_LINTS)
    for lint, level in RUST_LINTS.items():
        lines.append(f'{lint:<{pad}} = "{level}"')

    lines += ["", "[lints.clippy]"]

    # Gather all lint names for padding calculation
    all_names = [lint for group_lints in CLIPPY_LINTS.values() for lint, _ in group_lints]
    if fixable_lints_path:
        fixable_groups = parse_fixable_lints(fixable_lints_path)
        for group_lints in fixable_groups.values():
            all_names.extend(group_lints)
    pad = max(len(n) for n in all_names)

    # Recommended lints (deny/warn)
    for section, group_lints in CLIPPY_LINTS.items():
        lines.append(f"# --- {section} ---")
        for lint, level in group_lints:
            lines.append(f'{lint:<{pad}} = "{level}"')
        lines.append("")

    # Fixable lints (allow) — skip any already covered by recommended
    if fixable_lints_path:
        fixable_groups = parse_fixable_lints(fixable_lints_path)
        lines.append("# --- Auto-fixable lints: silent during dev, auto-fixed at commit time ---")
        for group, lints in fixable_groups.items():
            filtered = [l for l in lints if l not in recommended_names]
            if not filtered:
                continue
            lines.append(f"# {group} ({len(filtered)} lints)")
            for lint in filtered:
                lines.append(f'{lint:<{pad}} = "allow"')
        lines.append("")

    return "\n".join(lines)


def emit_hook(fixable_lints_path: Path | None = None) -> str:
    """Emit the full recommended pre-commit hook.

    clippy::all (style+complexity+perf+suspicious), pedantic, and nursery
    are covered by group flags. Restriction lints have no group flag (the
    group contains contradictory pairs), so fixable restriction lints get
    individual -W flags.
    """
    # Groups covered by group-level flags
    GROUP_FLAGS = ["clippy::all", "clippy::pedantic", "clippy::nursery"]
    GROUPS_COVERED = {"style", "complexity", "perf", "suspicious", "pedantic", "nursery",
                      "correctness"}

    restriction_lints: list[str] = []
    if fixable_lints_path:
        fixable_groups = parse_fixable_lints(fixable_lints_path)
        for group, lints in fixable_groups.items():
            if group.lower() not in GROUPS_COVERED:
                restriction_lints.extend(lints)

    fix_flags = " \\\n".join([
        "cargo clippy --fix --allow-dirty --allow-staged --",
        *(f"  -W {flag}" for flag in GROUP_FLAGS),
        *(f"  -W clippy::{lint}" for lint in restriction_lints),
    ])

    banned_entries = "\n".join(
        f'  [{crate}]="{reason}"' for crate, reason in BANNED_CRATES.items()
    )

    return f"""#!/usr/bin/env bash
set -euo pipefail
# Auto-generated by scripts/recommended-config.py --format hook{f' --fixable-lints {fixable_lints_path}' if fixable_lints_path else ''}

# Use rg (ripgrep) for pattern matching if available, fall back to grep -E.
if command -v rg &>/dev/null; then
  _grep() {{ rg "$@"; }}
else
  _grep() {{ grep -E "$@"; }}
fi

# 0. Isolate staged content — stash unstaged changes so tools only see what
#    will be committed. A unique name lets us find this entry even if the hook
#    fails and is re-run.
staged=$(git diff --cached --name-only --diff-filter=ACM)
[[ -z "$staged" ]] && exit 0

# Skip entirely when no Rust-relevant files are staged (e.g. docs-only commits).
echo "$staged" | _grep '\\.rs$|Cargo\\.toml$' || exit 0

stash_name="pre-commit-$(date +%s)"
git stash push --keep-index --include-untracked -q -m "$stash_name"
trap 'git stash list | grep -qF "$stash_name" && git stash pop -q || true' EXIT

# 1. Auto-fix idioms — always-correct machine-applicable fixes applied silently.
#    Fixed-point loop: --fix skips fixes with overlapping spans, so a single
#    pass can leave unfixed code. Loop until clippy reports no more fixes.
for (( i=0; i<5; i++ )); do
  output=$({fix_flags} 2>&1)
  echo "$output" | _grep -q 'Fixed' || break
done
# Print only if there are unresolved diagnostics (errors or named warnings).
if echo "$output" | _grep -q '^error|^warning\\['; then
  echo "$output"
fi

# 2. Check for debug remnants — runs after auto-fix so cleaned-up code is checked too.
cargo dylint debug_remnants --warn || true

# 3. Format only staged .rs files.
echo "$staged" | _grep '\\.rs$' | xargs -r rustfmt

# 4. Re-stage only originally-staged files modified by auto-fix and formatting.
echo "$staged" | xargs -r git add

# 5. Check for banned crates — catches additions at the point they enter Cargo.toml.
declare -A BANNED=(
{banned_entries}
)

rc=0
while IFS= read -r toml; do
  for crate in "${{!BANNED[@]}}"; do
    if _grep -q "^[[:space:]]*${{crate}}[[:space:]]*(=|\\{{)" "$toml"; then
      echo "banned dependency '${{crate}}' in ${{toml}} — ${{BANNED[$crate]}}"
      rc=1
    fi
  done
done < <(echo "$staged" | _grep 'Cargo\\.toml$')

exit $rc
"""


def do_install(fixable_lints_path: Path | None = None) -> None:
    """Install pre-commit hook and print lint config for Cargo.toml."""
    root = Path.cwd()
    if not (root / "Cargo.toml").exists():
        print("error: no Cargo.toml found in current directory", file=sys.stderr)
        sys.exit(1)

    hooks_dir = root / ".githooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_path = hooks_dir / "pre-commit"
    hook_path.write_text(emit_hook(fixable_lints_path))
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"wrote {hook_path}")

    print()
    print("Add the following to your Cargo.toml (or merge with existing [lints] sections):")
    print()
    print(emit_lints(fixable_lints_path))
    print()
    print("Then run:  git config core.hooksPath .githooks")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--format",
        choices=["lints", "hook"],
        help="Output format",
    )
    parser.add_argument(
        "--fixable-lints",
        type=Path,
        help="Path to fixable lints TOML (from scrape-clippy-applicability.py --format cargo-toml)",
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="Install pre-commit hook and print lint config",
    )
    args = parser.parse_args()

    if args.install:
        do_install(args.fixable_lints)
        return

    if not args.format:
        parser.error("--format or --install required")

    if args.format == "lints":
        print(emit_lints(args.fixable_lints))
    elif args.format == "hook":
        print(emit_hook(args.fixable_lints))


if __name__ == "__main__":
    main()
